#!/bin/sh

sxhkd &

# autostart programs
wmname LG3D

feh --bg-fill -d /home/vegard/.config/bspwm/wallpapers/13.jpg

# keyboard switch function
setxkbmap -option grp:shifts_toggle us,no &

# Notification manager
dunst &

# Tray bar
stalonetray &

# redshift
~/.config/redshift/redshift.sh

# compositor
~/.config/compton/launch_compton

# status bar
~/.config/polybar/launch.sh


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# window settings
bspc config focused_border_width         3
bspc config focused_border_color         '#aa00aa'
bspc config window_gap           12
bspc config top_padding		 0
bspc config bottom_padding	 0
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      false
bspc config focus_follows_pointer  true
bspc config border_radius 6


# application rules
bspc rule -a Gimp state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a lutris state=pseudo_tiled 
bspc rule -a Emacs state=tiled
bspc rule -a Vmware state=tiled
bspc rule -a Vmplayer state=tiled
bspc rule -a QjackCtl state=pseudo_tiled
bspc rule -a Guitarix state=tiled
bspc rule -a pycharm state=pseudo_tiled follow=off
